### ISSUE TITLE
Unable to run the latest version of package.

### ISSUE THREAD

**Issue by rgierczak** [piecioshka/wooden-ladder#1]
The latest version of package doesn't work on our lead project, where the package has been included.
We have an error visible in console :

```
Uncaught ReferenceError: module is not defined
Uncaught TypeError: WoodenLadder is not a constructor
```

I suppose the `main` entry in `package.json` shall point into `dist` directory, except the root one.

**Comment by piecioshka** [comment]
Closed by #2
